### ISSUE TITLE
ModuleNotFoundError: No module named 'libclair3'

### ISSUE THREAD

**Issue by LichungKuo** [HKU-BAL/Clair3#138]
Hello, I am new to Linux and the sequencing world, I have tried Clair3 using the code that you provided on ont_quick_demo, but I received the error messages like: import libclair3 / ModuleNotFoundError: No module named 'libclair3'.

There's no page that talks about libclair3. Do I miss something? How can I fix it?
I am willing to share my script if you would need it.

Thank you in advance.

**Comment by zhengzhenxian** [comment]
Hi,
Could you share your demo script for us to pinpoint the issue? Thanks!

**Comment by LichungKuo** [comment]
> Hi, Could you share your demo script for us to pinpoint the issue? Thanks!

Thanks for your reply, I found the problem. I think it is because of Installation Option 4. Build an anaconda virtual environment "make PREFIX=${CONDA_PREFIX}". Error message: "make: *** [libclair3.so] Error 1"


Thanks again.

`(base) [r10455003@lgn303 Clair3]$ source activate clair3 && make PREFIX=${CONDA_PREFIX}
python3 build.py
/home/r10455003/miniconda3/envs/clair3/lib/python3.9/site-packages/cffi/cparser.py:154: UserWarning: String literal found in cdef() or type source. String literals are ignored here, but you should remove them anyway because some character sequences confuse pre-parsing.
  warnings.warn("String literal found in cdef() or type source. "
generating ./libclair3.c
(already up-to-date)
the current directory is '/home/r10455003/Clair3'
running build_ext
building 'libclair3' extension
gcc -pthread -B /home/r10455003/miniconda3/envs/clair3/compiler_compat -Wl,--sysroot=/ -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/r10455003/miniconda3/envs/clair3/include -fPIC -O2 -isystem /home/r10455003/miniconda3/envs/clair3/include -fPIC -I/home/r10455003/Clair3/src -I/home/r10455003/Clair3/samtools-1.15.1/htslib-1.15.1 -I/home/r10455003/miniconda3/envs/clair3/include/python3.9 -c /home/r10455003/Clair3/src/clair3_full_alignment.c -o ./home/r10455003/Clair3/src/clair3_full_alignment.o -std=c99 -O3 -mtune=haswell
/home/r10455003/Clair3/src/clair3_full_alignment.c:1:0: 錯誤：bad value (haswell) for -mtune= switch
 #define _GNU_SOURCE
 ^
Traceback (most recent call last):
  File "/home/r10455003/miniconda3/envs/clair3/lib/python3.9/site-packages/setuptools/_distutils/unixccompiler.py", line 186, in _compile
    self.spawn(compiler_so + cc_args + [src, '-o', obj] + extra_postargs)
  File "/home/r10455003/miniconda3/envs/clair3/lib/python3.9/site-packages/setuptools/_distutils/ccompiler.py", line 1007, in spawn
    spawn(cmd, dry_run=self.dry_run, **kwargs)
  File "/home/r10455003/miniconda3/envs/clair3/lib/python3.9/site-packages/setuptools/_distutils/spawn.py", line 70, in spawn
    raise DistutilsExecError(
distutils.errors.DistutilsExecError: command '/usr/bin/gcc' failed with exit code 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/r10455003/miniconda3/envs/clair3/lib/python3.9/site-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/home/r10455003/miniconda3/envs/clair3/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/r10455003/miniconda3/envs/clair3/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
    cmd_obj.run()
  File "/home/r10455003/miniconda3/envs/clair3/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/home/r10455003/miniconda3/envs/clair3/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
    self.build_extensions()
  File "/home/r10455003/miniconda3/envs/clair3/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 466, in build_extensions
    self._build_extensions_serial()
  File "/home/r10455003/miniconda3/envs/clair3/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 492, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/r10455003/miniconda3/envs/clair3/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/r10455003/miniconda3/envs/clair3/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 547, in build_extension
    objects = self.compiler.compile(
  File "/home/r10455003/miniconda3/envs/clair3/lib/python3.9/site-packages/setuptools/_distutils/ccompiler.py", line 599, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/home/r10455003/miniconda3/envs/clair3/lib/python3.9/site-packages/setuptools/_distutils/unixccompiler.py", line 188, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command '/usr/bin/gcc' failed with exit code 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/r10455003/Clair3/build.py", line 74, in <module>
    ffibuilder.compile(verbose=True)
  File "/home/r10455003/miniconda3/envs/clair3/lib/python3.9/site-packages/cffi/api.py", line 725, in compile
    return recompile(self, module_name, source, tmpdir=tmpdir,
  File "/home/r10455003/miniconda3/envs/clair3/lib/python3.9/site-packages/cffi/recompiler.py", line 1564, in recompile
    outputfilename = ffiplatform.compile('.', ext,
  File "/home/r10455003/miniconda3/envs/clair3/lib/python3.9/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/r10455003/miniconda3/envs/clair3/lib/python3.9/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.VerificationError: CompileError: command '/usr/bin/gcc' failed with exit code 1
make: *** [libclair3.so] Error 1`

**Comment by zhengzhenxian** [comment]
Hi, seem an error when using gcc compile for `Error：bad value (haswell) for -mtune= switch` parameter, not sure it is relevant with your gcc version(v7.5 work in our local enviroment). 

You might try to install via [bioconda](https://github.com/HKU-BAL/Clair3#option-3--bioconda) or [Docker pre-built image](https://github.com/HKU-BAL/Clair3#option-1--docker-pre-built-image), which have automatically included libclair3 submodule.

**Comment by GuardSkill** [comment]
I use mamba to alter the conda ,  and get this error. are you use mamba too?

**Comment by koujiaodahan** [comment]
> Hi, seem an error when using gcc compile for `Error：bad value (haswell) for -mtune= switch` parameter, not sure it is relevant with your gcc version(v7.5 work in our local enviroment).
> 
> You might try to install via [bioconda](https://github.com/HKU-BAL/Clair3#option-3--bioconda) or [Docker pre-built image](https://github.com/HKU-BAL/Clair3#option-1--docker-pre-built-image), which have automatically included libclair3 submodule.

I use miniconda as instructed ,but in front the same error
