### ISSUE TITLE
RuntimeError: Unsuccessful TensorSliceReader constructor

### ISSUE THREAD

**Issue by ogrecio** [HKU-BAL/Clair3#140]
Hi,
I installed clair3 using a conda environment.
I'm having this error when calling variants and using several models. 
I used kit 114 for sequencing and guppy 6.3.7 for sup basecalling. What would be the preferred trained model to use?

In any case, the error seems to be caused by TensorFlow: See details below.
Thank you!

`
MODEL_NAME=" r941_prom_sup_g5014"               # "r941_prom_sup_g5014"
run_clair3.sh --bam_fn=$WD/Mapped/$sampleID.srt.trimm.fastq.bam --ref_fn=$referenceGenome/Bos_taurus.ARS-UCD1.2.dna.primary_assembly.fa --vcf_fn=$referenceGenome/Genome-Run7-TAU-Beagle-fixed-SNPsMAF.vcf.gz --no_phasing_for_fa --remove_intermediate_dir --threads=36 --platform="ont" --model_path="${CONDA_PREFIX}/bin/models/${MODEL_NAME}" --output=Clair3.$sampleID
/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/run_clair3.sh: line 176: [: /mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/models/: binary operator expected
[WARNING] No absolute output path provided, using current directory as prefix
[INFO] CLAIR3 VERSION: v0.1-r11
[INFO] BAM FILE PATH: /mnt/lustre/scratch/nlsas/home/csic/mgr/ogr/lowpass/Mapped/3130.conDuplex.srt.trimm.fastq.bam
[INFO] REFERENCE FILE PATH: /mnt/lustre/scratch/nlsas//home/csic/mgr/ogr/ReferenceGenomes/ARS-UCD1.2//Bos_taurus.ARS-UCD1.2.dna.primary_assembly.fa
[INFO] MODEL PATH: /mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/models/ r941_prom_sup_g5014
[INFO] OUTPUT FOLDER: /mnt/lustre/scratch/nlsas/home/csic/mgr/ogr/lowpass/Clair3.3130.conDuplex
[INFO] PLATFORM: ont
[INFO] THREADS: 36
[INFO] BED FILE PATH: EMPTY
[INFO] VCF FILE PATH: /mnt/lustre/scratch/nlsas//home/csic/mgr/ogr/ReferenceGenomes/ARS-UCD1.2//Genome-Run7-TAU-Beagle-fixed-SNPsMAF.vcf.gz
[INFO] CONTIGS: EMPTY
[INFO] CONDA PREFIX: /mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3
[INFO] SAMTOOLS PATH: samtools
[INFO] PYTHON PATH: python3
[INFO] PYPY PATH: pypy3
[INFO] PARALLEL PATH: parallel
[INFO] WHATSHAP PATH: whatshap
[INFO] LONGPHASE PATH: EMPTY
[INFO] CHUNK SIZE: 5000000
[INFO] FULL ALIGN PROPORTION: 0.7
[INFO] FULL ALIGN REFERENCE PROPORTION: 0.1
[INFO] PHASING PROPORTION: 0.7
[INFO] MINIMUM MQ: 5
[INFO] MINIMUM COVERAGE: 2
[INFO] SNP AF THRESHOLD: 0.08
[INFO] INDEL AF THRESHOLD: 0.15
[INFO] ENABLE FILEUP ONLY CALLING: False
[INFO] ENABLE FAST MODE CALLING: False
[INFO] ENABLE CALLING SNP CANDIDATES ONLY: False
[INFO] ENABLE PRINTING REFERENCE CALLS: False
[INFO] ENABLE OUTPUT GVCF: False
[INFO] ENABLE HAPLOID PRECISE MODE: False
[INFO] ENABLE HAPLOID SENSITIVE MODE: False
[INFO] ENABLE INCLUDE ALL CTGS CALLING: False
[INFO] ENABLE NO PHASING FOR FULL ALIGNMENT: True
[INFO] ENABLE REMOVING INTERMEDIATE FILES: True
[INFO] ENABLE PHASING VCF OUTPUT: False
[INFO] ENABLE LONG INDEL CALLING: False
[INFO] ENABLE LONGPHASE_FOR_PHASING: False
[INFO] ENABLE C_IMPLEMENT: True

/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/run_clair3.sh: line 290: [: /mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/models/: binary operator expected
/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/run_clair3.sh: line 291: [: /mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/models/: binary operator expected
/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/run_clair3.sh: line 339: [: /mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/models/: binary operator expected
/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/run_clair3.sh: line 340: [: /mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/models/: binary operator expected
+ /mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/scripts/clair3_c_impl.sh --bam_fn /mnt/lustre/scratch/nlsas/home/csic/mgr/ogr/lowpass/Mapped/3130.conDuplex.srt.trimm.fastq.bam --ref_fn /mnt/lustre/scratch/nlsas//home/csic/mgr/ogr/ReferenceGenomes/ARS-UCD1.2//Bos_taurus.ARS-UCD1.2.dna.primary_assembly.fa --threads 36 --model_path /mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/models/ r941_prom_sup_g5014 --platform ont --output /mnt/lustre/scratch/nlsas/home/csic/mgr/ogr/lowpass/Clair3.3130.conDuplex --bed_fn=EMPTY --vcf_fn=/mnt/lustre/scratch/nlsas//home/csic/mgr/ogr/ReferenceGenomes/ARS-UCD1.2//Genome-Run7-TAU-Beagle-fixed-SNPsMAF.vcf.gz --ctg_name=EMPTY --sample_name=SAMPLE --chunk_num=0 --chunk_size=5000000 --samtools=samtools --python=python3 --pypy=pypy3 --parallel=parallel --whatshap=whatshap --qual=2 --var_pct_full=0.7 --ref_pct_full=0.1 --var_pct_phasing=0.7 --snp_min_af=0.08 --indel_min_af=0.15 --min_mq=5 --min_coverage=2 --min_contig_size=0 --pileup_only=False --gvcf=False --fast_mode=False --call_snp_only=False --print_ref_calls=False --haploid_precise=False --haploid_sensitive=False --include_all_ctgs=False --no_phasing_for_fa=True --pileup_model_prefix=pileup --fa_model_prefix=full_alignment --remove_intermediate_dir=True --enable_phasing=False --enable_long_indel=False --use_gpu=False --longphase_for_phasing=False --longphase=EMPTY

[INFO] Check environment variables
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
[INFO] --include_all_ctgs not enabled, use chr{1..22,X,Y} and {1..22,X,Y} by default
[INFO] Call variant in contigs: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 X 28 24 26 25 23 29 27
[INFO] Chunk number for each contig: 32 28 25 25 25 24 23 23 22 21 22 18 17 17 18 17 15 14 13 15 14 13 28 10 13 11 9 11 11 10
[INFO] 1/7 Call variants using pileup model
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
Traceback (most recent call last):
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/lib/python3.6/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 95, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern))
RuntimeError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/models//pileup

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/scripts/../clair3.py", line 94, in <module>
    main()
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/scripts/../clair3.py", line 88, in main
    submodule.main()
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/clair3/CallVariantsFromCffi.py", line 339, in main
    Run(args)
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/clair3/CallVariantsFromCffi.py", line 61, in Run
    call_variants_from_cffi(args=args, output_config=output_config, output_utilities=output_utilities)
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/clair3/CallVariantsFromCffi.py", line 99, in call_variants_from_cffi
    m.load_weights(args.chkpnt_fn)
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 250, in load_weights
    return super(Model, self).load_weights(filepath, by_name, skip_mismatch)
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1231, in load_weights
    py_checkpoint_reader.NewCheckpointReader(filepath)
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/lib/python3.6/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 99, in NewCheckpointReader
    error_translator(e)
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/lib/python3.6/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 35, in error_translator
    raise errors_impl.NotFoundError(None, None, error_message)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/models//pileup
Traceback (most recent call last):
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/lib/python3.6/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 95, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern))
RuntimeError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/models//pileup

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/scripts/../clair3.py", line 94, in <module>
    main()
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/scripts/../clair3.py", line 88, in main
    submodule.main()
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/clair3/CallVariantsFromCffi.py", line 339, in main
    Run(args)
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/clair3/CallVariantsFromCffi.py", line 61, in Run
    call_variants_from_cffi(args=args, output_config=output_config, output_utilities=output_utilities)
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/clair3/CallVariantsFromCffi.py", line 99, in call_variants_from_cffi
    m.load_weights(args.chkpnt_fn)
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 250, in load_weights
    return super(Model, self).load_weights(filepath, by_name, skip_mismatch)
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1231, in load_weights
    py_checkpoint_reader.NewCheckpointReader(filepath)
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/lib/python3.6/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 99, in NewCheckpointReader
    error_translator(e)
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/lib/python3.6/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 35, in error_translator
    raise errors_impl.NotFoundError(None, None, error_message)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/models//pileup
Traceback (most recent call last):
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/lib/python3.6/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 95, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern))
RuntimeError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/models//pileup

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/scripts/../clair3.py", line 94, in <module>
    main()
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/scripts/../clair3.py", line 88, in main
    submodule.main()
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/clair3/CallVariantsFromCffi.py", line 339, in main
    Run(args)
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/clair3/CallVariantsFromCffi.py", line 61, in Run
    call_variants_from_cffi(args=args, output_config=output_config, output_utilities=output_utilities)
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/clair3/CallVariantsFromCffi.py", line 99, in call_variants_from_cffi
    m.load_weights(args.chkpnt_fn)
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 250, in load_weights
    return super(Model, self).load_weights(filepath, by_name, skip_mismatch)
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1231, in load_weights
    py_checkpoint_reader.NewCheckpointReader(filepath)
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/lib/python3.6/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 99, in NewCheckpointReader
    error_translator(e)
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/lib/python3.6/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 35, in error_translator
    raise errors_impl.NotFoundError(None, None, error_message)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/models//pileup
Traceback (most recent call last):
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/lib/python3.6/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 95, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern))
RuntimeError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/models//pileup

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/scripts/../clair3.py", line 94, in <module>
    main()
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/scripts/../clair3.py", line 88, in main
    submodule.main()
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/clair3/CallVariantsFromCffi.py", line 339, in main
    Run(args)
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/clair3/CallVariantsFromCffi.py", line 61, in Run
    call_variants_from_cffi(args=args, output_config=output_config, output_utilities=output_utilities)
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/clair3/CallVariantsFromCffi.py", line 99, in call_variants_from_cffi
    m.load_weights(args.chkpnt_fn)
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 250, in load_weights
    return super(Model, self).load_weights(filepath, by_name, skip_mismatch)
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1231, in load_weights
    py_checkpoint_reader.NewCheckpointReader(filepath)
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/lib/python3.6/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 99, in NewCheckpointReader
    error_translator(e)
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/lib/python3.6/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 35, in error_translator
    raise errors_impl.NotFoundError(None, None, error_message)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/models//pileup
Traceback (most recent call last):
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/lib/python3.6/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 95, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern))
RuntimeError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/models//pileup

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/scripts/../clair3.py", line 94, in <module>
    main()
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/scripts/../clair3.py", line 88, in main
    submodule.main()
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/clair3/CallVariantsFromCffi.py", line 339, in main
    Run(args)
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/clair3/CallVariantsFromCffi.py", line 61, in Run
    call_variants_from_cffi(args=args, output_config=output_config, output_utilities=output_utilities)
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/clair3/CallVariantsFromCffi.py", line 99, in call_variants_from_cffi
    m.load_weights(args.chkpnt_fn)
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 250, in load_weights
    return super(Model, self).load_weights(filepath, by_name, skip_mismatch)
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1231, in load_weights
    py_checkpoint_reader.NewCheckpointReader(filepath)
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/lib/python3.6/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 99, in NewCheckpointReader
    error_translator(e)
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/lib/python3.6/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 35, in error_translator
    raise errors_impl.NotFoundError(None, None, error_message)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/models//pileup
Traceback (most recent call last):
  File "/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/lib/python3.6/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 95, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern))
RuntimeError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/models//pileup

During handling of the above exception, another exception occurred:

`

**Comment by zhengzhenxian** [comment]
Hi,
     it seems that there is a space in `MODEL_NAME=" r941_prom_sup_g5014"`, and python argument parser cannot parser the path `/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/models//pileup` to `/mnt/netapp1/Store_CSIC/home/csic/mgr/ogr/.conda/envs/clair3/bin/models/r941_prom_sup_g5014/pileup`correctly. 

And for Kit 114 chemistry, we recommend you use the correct ONT-provided model [here](https://github.com/HKU-BAL/Clair3#ont-provided-models), thanks!

**Comment by ogrecio** [comment]
Silly mistake. 
I downloaded the new models and all seems to work now.
Thank you.
