### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by oranges7** [HKU-BAL/Clair3#162]
If the amount of data is too large, the following errors will be reported. What parameters can I change to prevent errors?
[INFO] Delay 4 seconds before starting tensor creation ...
Loading the dataset ...
[mpileup] 1 samples in 1 input files
Note: detected 112 virtual cores but NumExpr set to maximum of 64, check "NUMEXPR_MAX_THREADS" environment variable.
Note: NumExpr detected 112 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
[INFO] Compressed 6456/99999 tensor
Finish!
Traceback (most recent call last):
  File "/home/gyc/anaconda3/envs/r12/bin/preprocess/../clair3.py", line 94, in <module>
    main()
  File "/home/gyc/anaconda3/envs/r12/bin/preprocess/../clair3.py", line 88, in main
    submodule.main()
  File "/home/gyc/anaconda3/envs/r12/bin/preprocess/CreateTensorFullAlignment.py", line 1057, in main
    CreateTensorFullAlignment(args)
  File "/home/gyc/anaconda3/envs/r12/bin/preprocess/CreateTensorFullAlignment.py", line 896, in CreateTensorFullAlignment
    tensor_can_fp.stdin.write(tensor)
BrokenPipeError: [Errno 32] Broken pipe

**Comment by zhengzhenxian** [comment]
Hi,
It seems like you are running out of memory, we would suggest using the latest version(v0.1-r12) with C implementation and setting a smaller CPU threading (using `--threads` option) to see if the issue persists, thanks!

Zhenxian

**Comment by oranges7** [comment]
OK, thank you for your reply. I'll try again.
