### ISSUE TITLE
errors in Pileup model fine-tune

### ISSUE THREAD

**Issue by huangnengCSU** [HKU-BAL/Clair3#19]
Hi, 
    I trained a Clair3 pileup model and the output in each epoch has 2 files. But in your official ONT pileup model, there are 3 corresponding files. I think the training procedure of pileup consists of two steps. The first training step makes the parameter `--add_indel_length` false and the second fine-tune step makes the parameter `--add_indel_length` true. But when I run fine-tune, there is some error information.
Step 1, training with --add_indel_length=False:
```
CUDA_VISIBLE_DEVICES=5 python3.6 /homeb/tools/Clair3/clair3.py Train \
--bin_fn /homeb/data/NA12878-SNP/clair3_train/output/build/bins/ \
--ochk_prefix clair3 \
--pileup \
--add_indel_length False \
--validation_dataset \
--platform ont
```
best epoch result:
```
(clair3) user@ubuntu:/homeb/data/NA12878-SNP/clair3_train/clair3/29/variables$ ls -l
total 16216
-rw-rw-r-- 1 user user 16594111 May 23 14:55 variables.data-00000-of-00001
-rw-rw-r-- 1 user user     4267 May 23 14:55 variables.index
```
Step 2, fine-tune with  --add_indel_length=True:
```
CUDA_VISIBLE_DEVICES=6 python3.6 /homeb/tools/Clair3/clair3.py Train \
--pileup \
--bin_fn "/homeb/data/NA12878-SNP/clair3_train/output/build/bins/" \
--ochk_prefix "/homeb/data/NA12878-SNP/clair3_train/clair3_add_indel" \
--add_indel_length True \
--validation_dataset \
--platform "ont" \
--learning_rate 0.0001 \
--chkpnt_fn "/homeb/data/NA12878-SNP/clair3_train/clair3/29"  ## use pre-trained pileup model here
```
Output error information:
```
2021-05-31 16:07:28.043909: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
/home/user/miniconda3/envs/clair3/lib/python3.6/site-packages/tensorflow_addons/utils/ensure_tf_install.py:68: UserWarning: Tensorflow Addons supports using Python ops for all Tensorflow versions above or equal to 2.2.0 and strictly below 2.4.0 (nightly versions are not supported). 
 The versions of TensorFlow you are currently using is 2.5.0 and is not supported. 
Some things might work, some things might not.
If you were to encounter a bug, do not file an issue.
If you want to make sure you're using a tested and supported configuration, either change the TensorFlow version or the TensorFlow Addons's version. 
You can find the compatibility matrix in TensorFlow Addon's readme:
https://github.com/tensorflow/addons
  UserWarning,
2021-05-31 16:07:29.909291: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
2021-05-31 16:07:33.781545: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:b1:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.545GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2021-05-31 16:07:33.781649: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2021-05-31 16:07:33.786525: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11
2021-05-31 16:07:33.786647: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublasLt.so.11
2021-05-31 16:07:33.788136: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcufft.so.10
2021-05-31 16:07:33.788627: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcurand.so.10
2021-05-31 16:07:33.790647: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusolver.so.11
2021-05-31 16:07:33.792302: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusparse.so.11
2021-05-31 16:07:33.792728: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudnn.so.8
2021-05-31 16:07:33.796474: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2021-05-31 16:07:33.796918: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-05-31 16:07:33.886699: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:b1:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.545GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2021-05-31 16:07:33.893519: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2021-05-31 16:07:33.893591: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2021-05-31 16:07:35.053465: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-05-31 16:07:35.053528: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0 
2021-05-31 16:07:35.053538: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N 
2021-05-31 16:07:35.057246: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9659 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:b1:00.0, compute capability: 7.5)
[INFO] total 22 training bin files: na12878_900_21_1,na12878_900_22_1,na12878_900_16_1,na12878_900_18_1,na12878_900_19_1,na12878_900_15_1,na12878_900_17_1,na12878_900_14_1,na12878_900_X_1,na12878_900_13_1,na12878_900_9_1,na12878_900_12_1,na12878_900_11_1,na12878_900_10_1,na12878_900_8_1,na12878_900_4_1,na12878_900_7_1,na12878_900_5_1,na12878_900_6_1,na12878_900_3_1,na12878_900_1_1,na12878_900_2_1
/home/user/miniconda3/envs/clair3/lib/python3.6/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:375: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  "The `lr` argument is deprecated, use `learning_rate` instead.")
2021-05-31 16:07:36.720948: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudnn.so.8
2021-05-31 16:07:41.337494: I tensorflow/stream_executor/cuda/cuda_dnn.cc:359] Loaded cuDNN version 8100
2021-05-31 16:07:41.585073: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11
2021-05-31 16:07:47.280088: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublasLt.so.11
Model: "clair3_p"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
bidirectional (Bidirectional multiple                  150528    
_________________________________________________________________
bidirectional_1 (Bidirection multiple                  533760    
_________________________________________________________________
dropout (Dropout)            multiple                  0         
_________________________________________________________________
flatten (Flatten)            multiple                  0         
_________________________________________________________________
dense (Dense)                multiple                  1351808   
_________________________________________________________________
dropout_1 (Dropout)          multiple                  0         
_________________________________________________________________
dense_1 (Dense)              multiple                  16512     
_________________________________________________________________
dropout_2 (Dropout)          multiple                  0         
_________________________________________________________________
dense_2 (Dense)              multiple                  16512     
_________________________________________________________________
dropout_3 (Dropout)          multiple                  0         
_________________________________________________________________
dense_3 (Dense)              multiple                  2709      
_________________________________________________________________
dense_4 (Dense)              multiple                  387       
_________________________________________________________________
softmax (Softmax)            multiple                  0         
=================================================================
Total params: 2,072,216
Trainable params: 2,072,216
Non-trainable params: 0
_________________________________________________________________
None
[INFO] The size of dataset: 20576250
[INFO] The training batch size: 2000
[INFO] The training learning_rate: 0.0001
[INFO] Total training steps: 277777
[INFO] Maximum training epoch: 30
[INFO] Start training...
2021-05-31 16:07:47.303398: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open /homeb/tools/Clair3_train/clair3/29: Failed precondition: /homeb/tools/Clair3_train/clair3/29; Is a directory: perhaps your file is in a different file format and you need to use a different restore operator?
2021-05-31 16:07:47.382239: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2021-05-31 16:07:47.400761: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2100000000 Hz
Epoch 1/30
Traceback (most recent call last):
  File "/homeb/tools/Clair3/clair3.py", line 89, in <module>
    main()
  File "/homeb/tools/Clair3/clair3.py", line 83, in main
    submodule.main()
  File "/homeb/tools/Clair3/clair3/Train.py", line 304, in main
    train_model(args)
  File "/homeb/tools/Clair3/clair3/Train.py", line 242, in train_model
    shuffle=False)
  File "/home/user/miniconda3/envs/clair3/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1183, in fit
    tmp_logs = self.train_function(iterator)
  File "/home/user/miniconda3/envs/clair3/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 889, in __call__
    result = self._call(*args, **kwds)
  File "/home/user/miniconda3/envs/clair3/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 933, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/home/user/miniconda3/envs/clair3/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 764, in _initialize
    *args, **kwds))
  File "/home/user/miniconda3/envs/clair3/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3050, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/home/user/miniconda3/envs/clair3/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3444, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/user/miniconda3/envs/clair3/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3289, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/user/miniconda3/envs/clair3/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 999, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/user/miniconda3/envs/clair3/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 672, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/user/miniconda3/envs/clair3/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 986, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /home/user/miniconda3/envs/clair3/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py:855 train_function  *
        return step_function(self, iterator)
    /home/user/miniconda3/envs/clair3/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py:845 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    /home/user/miniconda3/envs/clair3/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py:1285 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /home/user/miniconda3/envs/clair3/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py:2833 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /home/user/miniconda3/envs/clair3/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py:3608 _call_for_each_replica
        return fn(*args, **kwargs)
    /home/user/miniconda3/envs/clair3/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py:838 run_step  **
        outputs = model.train_step(data)
    /home/user/miniconda3/envs/clair3/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py:797 train_step
        y, y_pred, sample_weight, regularization_losses=self.losses)
    /home/user/miniconda3/envs/clair3/lib/python3.6/site-packages/tensorflow/python/keras/engine/compile_utils.py:187 __call__
        self.build(y_pred)
    /home/user/miniconda3/envs/clair3/lib/python3.6/site-packages/tensorflow/python/keras/engine/compile_utils.py:135 build
        self._losses = self._conform_to_outputs(y_pred, self._losses)
    /home/user/miniconda3/envs/clair3/lib/python3.6/site-packages/tensorflow/python/keras/engine/compile_utils.py:59 _conform_to_outputs
        struct = map_to_output_names(outputs, self._output_names, struct)
    /home/user/miniconda3/envs/clair3/lib/python3.6/site-packages/tensorflow/python/keras/engine/compile_utils.py:654 map_to_output_names
        struct.keys(), output_names))

    ValueError: Found unexpected keys that do not correspond to any Model output: dict_keys(['output_3', 'output_4']). Expected: ['output_1', 'output_2']

Closing remaining open files:/homeb/tools/Clair3_train/output/build/bins/na12878_900_18_1...done/homeb/tools/Clair3_train/output/build/bins/na12878_900_X_1...done/homeb/tools/Clair3_train/output/build/bins/na12878_900_10_1...done/homeb/tools/Clair3_train/output/build/bins/na12878_900_17_1...done/homeb/tools/Clair3_train/output/build/bins/na12878_900_22_1...done/homeb/tools/Clair3_train/output/build/bins/na12878_900_12_1...done/homeb/tools/Clair3_train/output/build/bins/na12878_900_7_1...done/homeb/tools/Clair3_train/output/build/bins/na12878_900_6_1...done/homeb/tools/Clair3_train/output/build/bins/na12878_900_2_1...done/homeb/tools/Clair3_train/output/build/bins/na12878_900_21_1...done/homeb/tools/Clair3_train/output/build/bins/na12878_900_4_1...done/homeb/tools/Clair3_train/output/build/bins/na12878_900_1_1...done/homeb/tools/Clair3_train/output/build/bins/na12878_900_19_1...done/homeb/tools/Clair3_train/output/build/bins/na12878_900_13_1...done/homeb/tools/Clair3_train/output/build/bins/na12878_900_10_1...done/homeb/tools/Clair3_train/output/build/bins/na12878_900_22_1...done/homeb/tools/Clair3_train/output/build/bins/na12878_900_17_1...done/homeb/tools/Clair3_train/output/build/bins/na12878_900_12_1...done/homeb/tools/Clair3_train/output/build/bins/na12878_900_8_1...done/homeb/tools/Clair3_train/output/build/bins/na12878_900_7_1...done/homeb/tools/Clair3_train/output/build/bins/na12878_900_6_1...done/homeb/tools/Clair3_train/output/build/bins/na12878_900_3_1...done/homeb/tools/Clair3_train/output/build/bins/na12878_900_2_1...done/homeb/tools/Clair3_train/output/build/bins/na12878_900_19_1...done/homeb/tools/Clair3_train/output/build/bins/na12878_900_13_1...done/homeb/tools/Clair3_train/output/build/bins/na12878_900_8_1...done/homeb/tools/Clair3_train/output/build/bins/na12878_900_16_1...done/homeb/tools/Clair3_train/output/build/bins/na12878_900_14_1...done/homeb/tools/Clair3_train/output/build/bins/na12878_900_11_1...done/homeb/tools/Clair3_train/output/build/bins/na12878_900_5_1...done/homeb/tools/Clair3_train/output/build/bins/na12878_900_3_1...done/homeb/tools/Clair3_train/output/build/bins/na12878_900_9_1...done/homeb/tools/Clair3_train/output/build/bins/na12878_900_15_1...done/homeb/tools/Clair3_train/output/build/bins/na12878_900_9_1...done/homeb/tools/Clair3_train/output/build/bins/na12878_900_4_1...done/homeb/tools/Clair3_train/output/build/bins/na12878_900_16_1...done/homeb/tools/Clair3_train/output/build/bins/na12878_900_14_1...done/homeb/tools/Clair3_train/output/build/bins/na12878_900_11_1...done/homeb/tools/Clair3_train/output/build/bins/na12878_900_5_1...done/homeb/tools/Clair3_train/output/build/bins/na12878_900_1_1...done/homeb/tools/Clair3_train/output/build/bins/na12878_900_21_1...done/homeb/tools/Clair3_train/output/build/bins/na12878_900_18_1...done/homeb/tools/Clair3_train/output/build/bins/na12878_900_15_1...done/homeb/tools/Clair3_train/output/build/bins/na12878_900_X_1...done
```

**Comment by aquaskyline** [comment]
Your step 1 has already generated a usable pileup model.

We made a mistake in `pileup_training.md` at line 322, and we doubt that has made you think step 2 is necessary. In the line, `--add_indel_length True` was incorrect. --add_indel_length is a full-alignment model only option. Noteworthy, different from Clair, Clair3's pileup model removed the two indel length tasks and retained only the 21-genotype task and the zygosity task. Thus `--add_indel_length True` in the guide is actually a development left-over. We have just removed `--add_indel_length True` from line 322. Thus would be enough for you to move on to the next steps I think. Meanwhile, we are also updating the guide and the code on this option to clarify it's only relevant to full-alignment model training.

**Comment by huangnengCSU** [comment]
@aquaskyline 
Thanks for your help. The fine-tune step runs successfully. And there is another question that the output pileup model I trained has only two files(first image) and the model you provided has three files(second image). If the numbers of model files are different, will the inference step succeed? And I don't know how to generate three model files.
![image](https://user-images.githubusercontent.com/28866823/120216092-23a06180-c269-11eb-89ca-57d6f59c55ee.png)
![image](https://user-images.githubusercontent.com/28866823/120216244-577b8700-c269-11eb-9983-0456b0dc0428.png)

Thanks
Neng Huang

**Comment by aquaskyline** [comment]
The number of files (one or two) is relevant to the TensorFlow version used. I believe your model is intact by looking at the file sizes. A quick way to test out is to remove the three pileup model files in a pretrained model and move in the two files of your new model (with prefixes change to `pileup.`), and try using the new model for inference.

We just found that our training guide has not mentioned the filename prefixes of the trained models should be changed to `pileup` and `full_alignment`, we will revise the guide.

**Comment by huangnengCSU** [comment]
@aquaskyline 
As you said, the number of output model files does not affect the inference step. Thanks for your help.

Best
Neng Huang
