### ISSUE TITLE
colab failed

### ISSUE THREAD

**Issue by yzhang-github-pub** [HKU-BAL/Clair3#192]
I tried Clair3 ONT quick demo in colab. It failed:

Traceback (most recent call last):
  File "/content/Clair3/scripts/../clair3.py", line 105, in <module>
    main()
  File "/content/Clair3/scripts/../clair3.py", line 99, in main
    submodule.main()
  File "/content/Clair3/preprocess/CheckEnvs.py", line 494, in main
    CheckEnvs(args)
  File "/content/Clair3/preprocess/CheckEnvs.py", line 267, in CheckEnvs
    check_tools_version(tool_version, required_tool_version)
  File "/content/Clair3/preprocess/CheckEnvs.py", line 64, in check_tools_version
    elif version < required_version:
  File "/usr/local/envs/clair3/lib/python3.6/distutils/version.py", line 52, in __lt__
    c = self._cmp(other)
  File "/usr/local/envs/clair3/lib/python3.6/distutils/version.py", line 337, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'str' and 'int'

**Comment by zhengzhenxian** [comment]
The colab script is served for demo only. You can add the branch before v0.1-r11 to test in the notebook as:`git clone https://github.com/HKU-BAL/Clair3.git -b v0.1-r10`.  

For the latest version, pls follow the [installations](https://github.com/HKU-BAL/Clair3#installation) to run Clair3 locally.
