### ISSUE TITLE
Running error during whatshap phase

### ISSUE THREAD

**Issue by yangao07** [HKU-BAL/Clair3#348]
Hi, I was using singularity, and here are the parameters and error info. 
Any suggestions are appreciated! 
Thank you!

```
[INFO] CLAIR3 VERSION: v1.0.9
[INFO] BAM FILE PATH: /homes2/yangao/data/HG002/HG002_PacBio-HiFi-Revio_20231031_48x_GRCh38-GIABv3.bam
[INFO] REFERENCE FILE PATH: /homes2/yangao/data/HG002/GRCh38_GIABv3_no_alt_analysis_set_maskedGRC_decoys_MAP2K3_KMT2C_KCNJ18.fasta.gz
[INFO] MODEL PATH: /opt/models/hifi_revio
[INFO] OUTPUT FOLDER: /homes2/yangao/data/HG002/Clair3
[INFO] PLATFORM: hifi
[INFO] THREADS: 16
[INFO] BED FILE PATH: EMPTY
[INFO] VCF FILE PATH: EMPTY
[INFO] CONTIGS: EMPTY
[INFO] CONDA PREFIX:
[INFO] SAMTOOLS PATH: samtools
[INFO] PYTHON PATH: python3
[INFO] PYPY PATH: pypy3
[INFO] PARALLEL PATH: parallel
[INFO] WHATSHAP PATH: whatshap
[INFO] LONGPHASE PATH: EMPTY
[INFO] CHUNK SIZE: 5000000
[INFO] FULL ALIGN PROPORTION: 0.3
[INFO] FULL ALIGN REFERENCE PROPORTION: 0.3
[INFO] PHASING PROPORTION: 0.7
[INFO] MINIMUM MQ: 5
[INFO] MINIMUM COVERAGE: 2
[INFO] SNP AF THRESHOLD: 0.08
[INFO] INDEL AF THRESHOLD: 0.08
[INFO] BASE ERROR IN GVCF: 0.001
[INFO] GQ BIN SIZE IN GVCF: 5
[INFO] ENABLE FILEUP ONLY CALLING: False
[INFO] ENABLE FAST MODE CALLING: False
[INFO] ENABLE CALLING SNP CANDIDATES ONLY: False
[INFO] ENABLE PRINTING REFERENCE CALLS: False
[INFO] ENABLE OUTPUT GVCF: False
[INFO] ENABLE HAPLOID PRECISE MODE: False
[INFO] ENABLE HAPLOID SENSITIVE MODE: False
[INFO] ENABLE INCLUDE ALL CTGS CALLING: False
[INFO] ENABLE NO PHASING FOR FULL ALIGNMENT: False
[INFO] ENABLE REMOVING INTERMEDIATE FILES: False
[INFO] ENABLE LONGPHASE FOR INTERMEDIATE VCF PHASING: False
[INFO] ENABLE PHASING FINAL VCF OUTPUT USING WHATSHAP: True
[INFO] ENABLE PHASING FINAL VCF OUTPUT USING LONGPHASE: False
[INFO] ENABLE HAPLOTAGGING FINAL BAM: True
[INFO] ENABLE LONG INDEL CALLING: False
[INFO] ENABLE C_IMPLEMENT: True

+ /opt/bin/scripts/clair3_c_impl.sh --bam_fn /homes2/yangao/data/HG002/HG002_PacBio-HiFi-Revio_20231031_48x_GRCh38-GIABv3.bam --ref_fn /homes2/yangao/data/HG002/GRCh38_GIABv3_no_alt_analysis_set_maskedGRC_decoys_MAP2K3_KMT2C_KCNJ18.fasta.gz --threads 16 --model_path /opt/models/hifi_revio --platform hifi --output /homes2/yangao/data/HG002/Clair3 --bed_fn=EMPTY --vcf_fn=EMPTY --ctg_name=EMPTY --sample_name=SAMPLE --chunk_num=0 --chunk_size=5000000 --samtools=samtools --python=python3 --pypy=pypy3 --parallel=parallel --whatshap=whatshap --qual=2 --var_pct_full=0.3 --ref_pct_full=0.3 --var_pct_phasing=0.7 --snp_min_af=0.08 --indel_min_af=0.08 --min_mq=5 --min_coverage=2 --min_contig_size=0 --pileup_only=False --gvcf=False --base_err=0.001 --gq_bin_size=5 --fast_mode=False --call_snp_only=False --print_ref_calls=False --haploid_precise=False --haploid_sensitive=False --include_all_ctgs=False --no_phasing_for_fa=False --pileup_model_prefix=pileup --fa_model_prefix=full_alignment --remove_intermediate_dir=False --enable_phasing=True --enable_long_indel=False --keep_iupac_bases=False --use_gpu=False --longphase_for_phasing=False --longphase=EMPTY --use_whatshap_for_intermediate_phasing=True --use_longphase_for_intermediate_phasing=False --use_whatshap_for_final_output_phasing=True --use_longphase_for_final_output_phasing=False --use_whatshap_for_final_output_haplotagging=True

... ...

[INFO] 3/7 Phase VCF file using Whatshap
This is WhatsHap 1.7 running under Python 3.9.0
[W::hts_idx_load3] The index file is older than the data file: /homes2/yangao/data/HG002/HG002_PacBio-HiFi-Revio_20231031_48x_GRCh38-GIABv3.bam.bai
[W::hts_idx_load3] The index file is older than the data file: /homes2/yangao/data/HG002/HG002_PacBio-HiFi-Revio_20231031_48x_GRCh38-GIABv3.bam.bai
Working on 1 sample from 1 family

# Working on contig chr16 in individual SAMPLE
Found 53463 usable heterozygous variants (0 skipped due to missing genotypes)
Traceback (most recent call last):
  File "/opt/conda/envs/clair3/bin/whatshap", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/envs/clair3/lib/python3.9/site-packages/whatshap/__main__.py", line 64, in main
    module.main(args)
  File "/opt/conda/envs/clair3/lib/python3.9/site-packages/whatshap/cli/phase.py", line 1169, in main
    run_whatshap(**vars(args))
  File "/opt/conda/envs/clair3/lib/python3.9/site-packages/whatshap/cli/phase.py", line 493, in run_whatshap
    readset, vcf_source_ids = phased_input_reader.read(
  File "/opt/conda/envs/clair3/lib/python3.9/site-packages/whatshap/cli/__init__.py", line 152, in read
    readset = readset_reader.read(chromosome, variants, bam_sample, reference, regions)
  File "/opt/conda/envs/clair3/lib/python3.9/site-packages/whatshap/variants.py", line 98, in read
    readset = self._make_readset_from_grouped_reads(grouped_reads)
  File "/opt/conda/envs/clair3/lib/python3.9/site-packages/whatshap/variants.py", line 104, in _make_readset_from_grouped_reads
    for group in groups:
  File "/opt/conda/envs/clair3/lib/python3.9/site-packages/whatshap/variants.py", line 119, in _group_paired_reads
    for read in reads:
  File "/opt/conda/envs/clair3/lib/python3.9/site-packages/whatshap/variants.py", line 166, in _alignments_to_reads
    reference = reference[:]
  File "/opt/conda/envs/clair3/lib/python3.9/site-packages/pyfaidx/__init__.py", line 920, in __getitem__
    return self._fa.get_seq(self.name, start + 1, stop)[::step]
  File "/opt/conda/envs/clair3/lib/python3.9/site-packages/pyfaidx/__init__.py", line 1149, in get_seq
    seq = self.faidx.fetch(name, start, end)
  File "/opt/conda/envs/clair3/lib/python3.9/site-packages/pyfaidx/__init__.py", line 727, in fetch
    seq = self.from_file(name, start, end)
  File "/opt/conda/envs/clair3/lib/python3.9/site-packages/pyfaidx/__init__.py", line 769, in from_file
    self.file.seek(i.offset)
  File "/opt/conda/envs/clair3/lib/python3.9/site-packages/Bio/bgzf.py", line 682, in seek
    self._load_block(start_offset)
  File "/opt/conda/envs/clair3/lib/python3.9/site-packages/Bio/bgzf.py", line 643, in _load_block
    block_size, self._buffer = _load_bgzf_block(handle, self._text)
  File "/opt/conda/envs/clair3/lib/python3.9/site-packages/Bio/bgzf.py", line 444, in _load_bgzf_block
    raise ValueError(
ValueError: A BGZF (e.g. a BAM file) block should start with b'\x1f\x8b\x08\x04', not b'T\x1bC!'; handle.tell() now says 37155
This is WhatsHap 1.7 running under Python 3.9.0
[W::hts_idx_load3] The index file is older than the data file: /homes2/yangao/data/HG002/HG002_PacBio-HiFi-Revio_20231031_48x_GRCh38-GIABv3.bam.bai
[W::hts_idx_load3] The index file is older than the data file: /homes2/yangao/data/HG002/HG002_PacBio-HiFi-Revio_20231031_48x_GRCh38-GIABv3.bam.bai
Working on 1 sample from 1 family

# Working on contig chr15 in individual SAMPLE
Found 53378 usable heterozygous variants (0 skipped due to missing genotypes)

... ...
```

**Comment by zhengzhenxian** [comment]
Hi @yangao07 

Seem a BAM  parser issue in WhatsHap. Could you try `--use_longphase_for_intermediate_phasing` that uses longphase for phasing? It gave a comparable performance with WhatsHap when coverage > 10x.

**Comment by yangao07** [comment]
Sure, then my command is like this, does it look good?
```
singularity exec \
  -B ${INPUT_DIR},${OUTPUT_DIR} \
  ${clair3_sif}                 \
  /opt/bin/run_clair3.sh        \
  -b ${in_bam}                  \
  -f ${ref_fa}                  \
  -t ${THREADS}                 \
  -p ${PLATFORM}                \
  -m /opt/models/${MODEL_NAME}  \
  --use_longphase_for_intermediate_phasing \
  --use_whatshap_for_final_output_phasing \
  --use_whatshap_for_final_output_haplotagging \
  -o ${OUTPUT_DIR}
```

**Comment by zhengzhenxian** [comment]
All good but might replace `--use_whatshap_for_final_output_phasing` by `--use_longphase_for_final_output_phasing`

**Comment by yangao07** [comment]
Thanks, longphase works for me!

One more question, for variant calling/phasing result, is using longphase very different from using whatshap?

**Comment by zhengzhenxian** [comment]
Great! 

In our benchmarking GIAB data, LongPhase gave a comparable performance with WhatsHap when coverage > 10x.
